# The Calculator app is configured to use skaffold modules.
# The frontend and backend services can be activated by name,
# allowing each service to be iterated on independently.

apiVersion: skaffold/v2beta18
kind: Config
build:
  local:
    concurrency: 0
requires:
  - path: ./src/frontend
  - path: ./src/backend
