# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: nodejs-calculator-frontend
    context: .
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
  statusCheckDeadlineSeconds: 300
portForward:
  - resourceType: service
    resourceName: nodejs-calculator-frontend
    port: 80
    localPort: 4503
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: buildpacks
  build:
    artifacts:
    - image: nodejs-calculator-frontend
      context: .
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        env:
        - GOOGLE_RUNTIME_VERSION=16.16.0
